### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by Kaleidosium** [MacDue/NESticlePort#1]
Hey Due, sorry for dropping contact with you, I thought you were dead, but thankfully you aren't.
anyway, I heard last time that the code is almost completed, just got to fix some minor issues. if you do not mind, could you tell me the status of it?, thank you very much.

**Comment by MacDue** [comment]
Sorry stuff happened: I did not get around to completing the code but (I think) my most recent changes are here: https://github.com/MacDue/NesticlePortSDL2 it runs & can load (some) games but there's emulation issues (with the emulator in the leaked source?) & no keyboard input.

**Comment by MacDue** [comment]
Feel free to fork it.

**Comment by MacDue** [comment]
It should be fairly easy to compile (but let me know if you run into any issues).

It requires C++17 to compile it (because I used std::filesystem). There's a makefile provided -- but I've only tried building on linux so far.

**Comment by MacDue** [comment]
![image](https://user-images.githubusercontent.com/11597044/72948856-56397080-3d7e-11ea-91cb-c5226884144f.png)
Just tested it: It needs C++17 (with std::filesystem linked), sdl2, and sdl2_image to compile.

**Comment by Kaleidosium** [comment]
Ah, okay, thanks Due
